### ISSUE TITLE
Add more preconfigured Antennae

### ISSUE THREAD

**Issue by Columbus240** [ryohpops/kspRemoteTechPlanner#1]
Since the last change, RemoteTech added many Antennae, so could please someone add them to the preconfigured set in the Planner.

**Comment by ryohpops** [comment]
The remaining four dishes are planned to be added as stocks, but I noticed they cause malfunction in Entire View. I'm working on it with top priority.

**Comment by ryohpops** [comment]
fixed by @06797c3
